"""added unique and check constraints

Revision ID: 1e855c4e5880
Revises: aad6c69a025a
Create Date: 2025-09-01 13:29:47.217374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e855c4e5880'
down_revision: Union[str, Sequence[str], None] = 'aad6c69a025a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tool_name', 'tools', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tool_name', 'tools', type_='unique')
    # ### end Alembic commands ###
