"""Add validation constraints

Revision ID: 26ff2693cfd8
Revises: [your_new_revision_id]
Create Date: 2025-09-06 19:02:26.992420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ff2693cfd8'
down_revision: Union[str, Sequence[str], None] = '[your_new_revision_id]'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workflow_steps_tool_id_fkey'), 'workflow_steps', type_='foreignkey')
    op.drop_constraint(op.f('workflow_steps_workflow_id_fkey'), 'workflow_steps', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_steps', 'tools', ['tool_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'workflow_steps', 'workflows', ['workflow_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_steps', type_='foreignkey')
    op.drop_constraint(None, 'workflow_steps', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_steps_workflow_id_fkey'), 'workflow_steps', 'workflows', ['workflow_id'], ['id'])
    op.create_foreign_key(op.f('workflow_steps_tool_id_fkey'), 'workflow_steps', 'tools', ['tool_id'], ['id'])
    # ### end Alembic commands ###
