"""Added metadata fields

Revision ID: aad6c69a025a
Revises: a8c75dbfe110
Create Date: 2025-08-30 21:46:00.478465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad6c69a025a'
down_revision: Union[str, Sequence[str], None] = 'a8c75dbfe110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tools', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow_steps', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('workflow_steps', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflows', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('workflows', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'updated_at')
    op.drop_column('workflows', 'created_at')
    op.drop_column('workflow_steps', 'updated_at')
    op.drop_column('workflow_steps', 'created_at')
    op.drop_column('tools', 'updated_at')
    op.drop_column('tools', 'created_at')
    # ### end Alembic commands ###
